[package]
name = "rust_explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
eframe = "0.27.2"
fs_extra = "1.3.0"
home = "0.5.9"
winapi = { version = "0.3.0", features = ["shellapi", "fileapi"] }

[profile.dev]
opt-level = 3
